spring:
  application:
    name: ANZWholesaleDemoApp
  profiles:
    active: dev
  datasource:
    url: jdbc:hsqldb:mem:wholesaleAppDB
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:

  jpa:
    database-platform: com.anz.wholesale.db.ImprovedH2Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081
  session:
    timeout: 1800
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

logging:
  level:
    com.anz.wholesale: INFO